name: dog_app
description: Dog App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # state management
  flutter_bloc: ^8.1.3

  # routing
  auto_route: ^7.8.4

  #networking
  http: ^0.13.5
  equatable: ^2.0.5

  #core
  flutter_native_splash: ^2.3.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/svg_icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_splash_icon.png
  android_12:
    image: assets/images/app_splash_icon.png